### ISSUE TITLE
Support services without a constructor

### ISSUE THREAD

**Issue by Serg046** [cdn77/dicc#3]
You are now requested to have a constructor even if you don't have any logic for that, otherwise you get the following:
```
[EE] No call or construct signatures found on service factory
```
That's the only reason why I have [this here](https://github.com/skyscrapercity-ru/skyscrapers/blob/main/src/components/table-row.ts#L27-L29).

**Comment by jahudka** [comment]
This works correctly now, not sure if / when I actually fixed it, but I was able to compile your container with the empty constructor in TableRow deleted, so I'll close this. If it ever happens again, feel free to reopen or start a new issue!
